## 실 운영 서버 yml - 처음 테스트 하고 나중에 gitignore 추가
#spring:
#  config:
#    activate:
#      on-profile: prod
#  jpa:
#    hibernate:
#      ddl-auto: none
#    properties:
#      hibernate:
#        format_sql: true